/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.text.ParseException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GraphicMx
 */
public class UpdateMedicine extends javax.swing.JFrame {

    public String numberPattern = "^[0-9]*$";
    private int checkMedicineExist;
    /**
     * Creates new form UpdateMedicine
     */
    public UpdateMedicine() {
        initComponents();
        setLocationRelativeTo(null);
        connect();
        update();
    }
  
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;
    
    public void connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacydistributionsystem?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void update()
    {
        
        String id = MedID.getText();
        String name = MedName.getText();
        String companyName = CompName.getText();
        String quantity = Quantity.getText();
        String upquantity = UpQuantity.getText();
        String price = Price.getText();
        String upprice = UpPrice.getText();
        String type = Type.getText();
        
        try {

            pst = this.con.prepareStatement("SELECT * From medicine Where WHERE MedicineID=?");
           if (jButton1.isSelected())
           {
           ResultSet rs = pst.executeQuery();
               while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= 7; i++) {
                    v2.add(rs.getString("ID"));
                    v2.add(rs.getString("MedicineID"));
                    v2.add(rs.getString("MedicineName"));
                    v2.add(rs.getString("CompanyName"));
                    v2.add(rs.getString("Price"));
                    v2.add(rs.getString("Quantity"));
                    v2.add(rs.getString("Type")); 
                    
            pst.setString(1, id);
            pst.setString(2, name);
            pst.setString(3, companyName);
            pst.setString(4, quantity);
            pst.setString(5, price);
            pst.setString(6, type);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Medicine Updated");

            MedID.setText("");
            MedName.setText("");
            CompName.setText("");
            Quantity.setText("");
            UpQuantity.setText("");
            Price.setText("");
            UpPrice.setText("");
            Type.setText("");
           }
        } 
           }
        }catch (SQLException ex) {
            Logger.getLogger(ViewMedicine.class.getName()).log(Level.SEVERE, null, ex);
     }


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        MedID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MedName = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CompName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Type = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        UpQuantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        UpPrice = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 15, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 71, 850, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 49, 66));
        jLabel2.setText("Medicine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 93, -1, -1));

        MedID.setForeground(new java.awt.Color(45, 49, 66));
        getContentPane().add(MedID, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 92, 271, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 49, 66));
        jLabel3.setText("Medicine Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 147, 112, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 49, 66));
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 197, 37, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 49, 66));
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 255, 72, -1));

        MedName.setForeground(new java.awt.Color(45, 49, 66));
        getContentPane().add(MedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 147, 224, -1));

        Price.setForeground(new java.awt.Color(45, 49, 66));
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 197, 224, -1));

        Quantity.setForeground(new java.awt.Color(45, 49, 66));
        getContentPane().add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 255, 216, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 49, 66));
        jLabel6.setText("Company Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 147, 109, -1));

        CompName.setForeground(new java.awt.Color(45, 49, 66));
        getContentPane().add(CompName, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 147, 224, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 49, 66));
        jLabel7.setText("Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 197, 37, -1));

        Type.setForeground(new java.awt.Color(45, 49, 66));
        getContentPane().add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 197, 224, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 49, 66));
        jLabel8.setText("Add Quantity");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 286, -1, -1));

        UpQuantity.setForeground(new java.awt.Color(45, 49, 66));
        getContentPane().add(UpQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 283, 80, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 49, 66));
        jLabel9.setText("Change Price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 228, -1, -1));

        UpPrice.setForeground(new java.awt.Color(45, 49, 66));
        getContentPane().add(UpPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 225, 81, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(45, 49, 66));
        jButton2.setText("Update");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 244, 91, 30));

        jPanel1.setBackground(new java.awt.Color(239, 131, 84));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(45, 49, 66));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(569, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jButton1)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        int checkMedicineExit = 0 ;
//        String// TODO add your handling code here:
//         uniqueId = MedID.getText();
//        if(uniqueId.equals(""))
//        {
//            JOptionPane.showMessageDialog(null, "Medicine ID field is required");
//        }
//        else{
//            try
//            {
//                Connection con = ConnectionProvider.getCon();
//                Statement st = con.createStatement();
//                ResultSet rs = st.executeQuery("");
//               PreparedStatement pst = this.con.prepareStatement("Select from Medicine where MedicineID=?");
//                while(rs.next())
//                {
//                    MedID.setEditable(false);
//                    MedName.setText(rs.getString("MedicineName"));
//                    CompName.setText(rs.getString("CompanyName"));
//                    Quantity.setText(rs.getString("Quantity"));
//                    Price.setText(rs.getString("Price"));
//                    Type.setText(rs.getString("Type"));
//                    Quantity.setEditable(false);
//                    Price.setEditable(false);
////                    checkMedicineExit == 1; 
//                }
//            }catch(Exception e)
//            {
//                JOptionPane.showMessageDialog(null, e);
//            }
//            if(checkMedicineExist == 0)
//            {
//                JOptionPane.showMessageDialog(null, "Medicine ID does not exist");
//            }
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CompName;
    private javax.swing.JTextField MedID;
    private javax.swing.JTextField MedName;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField Type;
    private javax.swing.JTextField UpPrice;
    private javax.swing.JTextField UpQuantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
